const configs = {
  BACKEND_API_BASE_URL: process.env.REACT_APP_BACKEND_API_BASE_URL || "",
  NWAY_API_BASE_URL: process.env.REACT_APP_NWAY_API_BASE_URL || "",
  BACKEND_API_OLY_BASE_URL:
    process.env.REACT_APP_BACKEND_API_OLY_BASE_URL || "",
  NWAY_API_BASE_OLY_URL: process.env.REACT_APP_NWAY_API_OLY_BASE_URL || "",
  GAME_TITLE: process.env.REACT_APP_GAME_TITLE || "",
  ENV: process.env.REACT_APP_ENV || "",
  NWAYPLAY_DOMAIN: process.env.REACT_APP_NWAYPLAY_DOMAIN || "",
  AMPLITUDE_KEY: process.env.REACT_APP_AMPLITUDE_KEY || "",
  TEST_NWAYPLAY_AUTH_TOKEN:
    process.env.REACT_APP_TEST_NWAYPLAY_AUTH_TOKEN || "",
  TEST_NWAYPLAY_AUTH_TOKEN_OLY:
    process.env.REACT_APP_TEST_NWAYPLAY_AUTH_TOKEN_OLY || "",
  TEST_NWAYPLAY_EMAIL: process.env.REACT_APP_TEST_NWAYPLAY_EMAIL || "",
  TEST_NWAYPLAY_DISPLAY_NAME:
    process.env.REACT_APP_TEST_NWAYPLAY_DISPLAY_NAME || "",
  // flow
  FLOW_ACCESS_NODE: process.env.REACT_APP_FLOW_ACCESS_NODE || "",
};

export default configs;
